version: '2'
services:
    jobsearapplchapplication-app:
        image: jobsearapplchapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jobsearapplchapplication-postgresql:5432/jobSearApplchApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jobsearapplchapplication-postgresql:
        extends:
            file: postgresql.yml
            service: jobsearapplchapplication-postgresql
